services:
    nginx:
        build: requirements/nginx
        container_name: nginx
        image: nginx:custom_nginx_hesayah
        restart: always
        env_file:
            - .env
        ports:
            - 443:443
        depends_on:
            - wordpress
        volumes:
            - wpress:/var/www/html
            - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - intern
    wordpress:
        build: requirements/wordpress
        container_name: wordpress
        image: wordpress:custom_wordpress_hesayah
        restart: always
        env_file:
            - .env
        depends_on:
            - mariadb
        volumes:
            - wpress:/var/www/html
            - ./requirements/wordpress/conf/www.conf:/etc/php/7.3/fpm/pool.d/www.conf
        networks:
            - intern
    mariadb:
        build: requirements/mariadb
        container_name: mariadb
        image:  mariadb:custom_mariadb_hesayah
        restart: always
        env_file:
            - .env        
        volumes:
          - dbase:/var/lib/mysql
          - ./requirements/mariadb/conf/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
        networks:
          - intern
networks:
    intern:
volumes:
    dbase:
        driver_opts:
            type: none
            o: bind
            device: "/home/hesayah/data/database"
    wpress:
        driver_opts:
            type: none
            o: bind
            device: "/home/hesayah/data/wordpress"